### ISSUE TITLE
MVP for Survey Interface

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#17]
Thinking about this I think the minimally viable approach is the following:

1. Questions will just be columns (attributes) for candidates. We'll hard code the question text into the candidate edit view.

2. Candidates will receive a link with their user login. A candidate can belong_to a user so that only the user that is associated with the candidate (or an admin) can edit the candidate profile.

3. Candidates will then update their own profile with the relevant info.

The question then becomes what editable information should exist for candidates in the view?

Bio?
Facebook link?
Twitter link?
Website?

+ I need the actual list of questions that we will include. I can always add more later but my guess is that candidates will only look and fill this out once so we'll have to have these questions before we send the survey to the candidates.

We'll save abstracting the surveys into its own module/model(s) for a future iteration.

**Comment by mzagaja** [comment]
Ok initial questions are added in. Users will need to be sent the direct link to where they edit their profile and also we will need to create a batch of candidate users that can edit their profiles before it goes live. In the meantime you can go to https://vote.ctnewsjunkie.com/districts/1 to see questions presented in the district view and then https://vote.ctnewsjunkie.com/candidates/1/edit to edit a candidate but only if you have permission to edit that particular candidate.

**Comment by mzagaja** [comment]
Doug if you make a user account on the staging server https://enigmatic-escarpment-35887.herokuapp.com then I'll link it to a candidate and give you a URL to see what it looks like.

**Comment by doughardy-ctnj** [comment]
done - let me know where to go to dive in

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=f90d8171-5228-44c5-f687-29aa5ef4128f>
(860) 543-9453 (mobile)

**Comment by doughardy-ctnj** [comment]
i think questions ought to be numbered and maybe we should put a square CTNJ logo next to them - a logo and identifier for each question
![ctnj-square-logo](https://cloud.githubusercontent.com/assets/22284125/19225037/90a2b522-8e60-11e6-94b2-d51ab4e29313.jpg)

**Comment by doughardy-ctnj** [comment]
maybe we don't need to number the questions but the logo (source of question) would be good

**Comment by doughardy-ctnj** [comment]
Thus far the bios don't say much about these folks. I think we need basic bio info and then a section where they answer questions.

Bio ought to include:
Name:
Age:
Marital status:
Current town of residence:
Profession/Current Job (Title & Company):
Previous Job:
Previous Job:
Education (School & Degree):
Party Affiliation:
CEP status:
Campaign Website:
Campaign Social Media:
Facebook:
Twitter:
Instagram:
Snapchat:
Periscope:

**Comment by mzagaja** [comment]
Yeah I think those fields make sense I can add them in.

**Comment by mzagaja** [comment]
The URL permissions should be fixed, try again on the Heroku link.

**Comment by doughardy-ctnj** [comment]
still getting the error at this link:
https://enigmatic-escarpment-35887.herokuapp.com/candidates/359/edit

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=3284380f-c272-498c-9172-09484240830e>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
Try a shift reload and/or a logout and then log back in. I just tested with a fresh new user that's not an admin and it worked fine.

**Comment by doughardy-ctnj** [comment]
fresh browser failed again - log out of what? vote.ctnewsjunkie.com?

**Comment by mzagaja** [comment]
No logout of the staging website https://enigmatic-escarpment-35887.herokuapp.com

**Comment by doughardy-ctnj** [comment]
no logout option anywhere

i tried creating a new user, see if that one works

**Comment by mzagaja** [comment]
No new user was created according to the admin panel. Are you sure you are going to https://enigmatic-escarpment-35887.herokuapp.com instead of https://vote.ctnewsjunkie.com/?

**Comment by doughardy-ctnj** [comment]
Just clicking on the link you sent.

**Comment by doughardy-ctnj** [comment]
now i'm just arriving at the site - no dashboard or place to click to access anything. 

can you send me the right credentials or just clear all the users and i'll start over

**Comment by doughardy-ctnj** [comment]
all my users

**Comment by mzagaja** [comment]
https://enigmatic-escarpment-35887.herokuapp.com/admin is the admin panel
link. There is no link to it on the website.
https://enigmatic-escarpment-35887.herokuapp.com/candidates/359/edit should
work after you are logged in
https://enigmatic-escarpment-35887.herokuapp.com/users/sign_in is the sign
in link and should work with the e-mail account/password you setup the
other day or you should be able to send yourself a reset password

-Matt

**Comment by doughardy-ctnj** [comment]
the pw reset gives me an error
i'm sorry for the problems

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=de81fd26-8d7c-443c-8bcc-034a2ecc2992>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
We were going to have to fix it eventually, trying to figure it out now.

**Comment by mzagaja** [comment]
Ok password resets should work now. Try again.

**Comment by doughardy-ctnj** [comment]
The pw reset was just taking me back to the home page.

I think it would be smart to delete my candidate user account and start
over - I'm generally not completely incompetent but I think something's
amiss.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.signauxdeux.com/e1t/c/5/f18dQhb0SmZ58dDMPbW2n0x6l2B9nMJW7sM9dn7dK_MMdBzM2-04?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=23797e7a-d3b3-4901-86e1-f0fe07e9678b>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
Ok deleted it, try again.

**Comment by doughardy-ctnj** [comment]
tried to log in with safari - when i use the pw reset, i get to the screen,
type in the new pw and then I'm endlessly prompted to ​allow safari to use
my confidential info stored in ctnewsjunkie.com in my keychain

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=b73e9a7f-86ec-49f0-8d70-961b5caa367f>
(860) 543-9453 (mobile)

**Comment by doughardy-ctnj** [comment]
just failing miserably pretty much doesn't matter what i do
[image: Inline image 1]

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://imnct.com/>
(860) 543-9453 (mobile)

**Comment by doughardy-ctnj** [comment]
gotta hit the sack, am out of focus
thanks for bearing with me tonight

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=b3de2c1a-0578-474b-cd2e-bacd175b321a>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
According to my side you successfully logged in. Maybe try using Google
Chrome? I added your new user to Toni Walker so once you are logged in this
link should work:
https://enigmatic-escarpment-35887.herokuapp.com/candidates/371/edit

**Comment by doughardy-ctnj** [comment]
got the error again just clicking on that link

i do use chrome btw

last night i was switching from chrome to safari and trying to clear cache
etc

i've got to get a contract over to a client but will circle back. apologies
for this - last night and today have been kind of difficult here with the
baby and other urgent work. will try to focus more shortly.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=9fca0bfb-56bd-472d-9dab-ed505bed68e6>
(860) 543-9453 (mobile)

**Comment by doughardy-ctnj** [comment]
i should switch to a newer laptop as well, perhaps. i am using a 2009
macbook pro that can be quirky. i have a new one waiting in the wings.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=746784fd-3b6c-4457-8cd9-c53a17d524ce>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
I'm going to be out of pocket tonight and tomorrow for my friend's wedding. I'm able to successfully create a brand new user account, login with it, and go to a survey user that I associate on my end. My logging also indicates that you successfully logged in once. So nothing appears to be "broken" on my end. So the only possibilities are:

1. Some piece of software in your computer is configured in a way that is preventing the sign in from working. This could include Adblock. It might be worth trying from another machine. I think this is the most likely thing because my logs show you trying to access the edit page but also show you as not being logged in when you are attempting to access the page which is why it is failing.

2. While I'm asking you to type and click things in text here, you might be interpreting that as clicking other things, or you might be taking a different step from what I think you are taking, and therefore it's a communication failure and we really just need to hop on a screen share to get it working.

**Comment by doughardy-ctnj** [comment]
yes screen share would be smart - but i'll migrate this project (my parts
of it) over to the newer laptop as well. i'm not understanding what the
problems are and when things just don't seem to work and don't show an
obvious reason, it suggest to me the browser config or the way the
browser's working with the OS etc. Not the first time we've had weird
things happen. For a long time, I was unable to see some of our ads from
our connection because it was comcast, and the ad serving company had to
migrate to a new server to clear it up. It was like a forensic mystery. I
went through an Apple router in the process.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=49191ad3-77c6-4c43-ff0d-0b00ec8bfcae>
(860) 543-9453 (mobile)

**Comment by doughardy-ctnj** [comment]
I may have discovered the problem... I attempted to reset my candidate user pw from the app:

https://enigmatic-escarpment-35887.herokuapp.com/users/sign_in

But when I get the pw reset email, it sends me to here:

https://vote.ctnewsjunkie.com/users/password/edit?reset_password_token=GNRxt6C4S8yRszQQ4Gkk

**Comment by doughardy-ctnj** [comment]
And then I get the reset password token is invalid message

**Comment by mzagaja** [comment]
Ok so in the password reset e-mail you should be able to get it to work by replacing the vote.ctnewsjunkie.com portion of the url with enigmatic-escarpment-35887.herokuapp.com.

**Comment by doughardy-ctnj** [comment]
Another question for the list:

Does Connecticut have a revenue problem or a spending problem?

**Comment by doughardy-ctnj** [comment]
In terms of delineating which questions came from which sponsor - I'm hoping we can add a clickable 100x100 logo next to each one (or smaller, 75x75 whatever works) and maybe a line above the specific question like "Sponsored by XYZ" .... italics or something

**Comment by mzagaja** [comment]
Ok updated with the logo.

**Comment by doughardy-ctnj** [comment]
those look good - ideally they will all be sponsored questions so the logos differ

**Comment by doughardy-ctnj** [comment]
The question "Do you support Hillary Clinton or Donald Trump for president? Why or why not?" shows some bias... we should change it to:

Who are you supporting for president? Why or why not?

**Comment by doughardy-ctnj** [comment]
_This question is sponsored by AARP Connecticut_
Will you oppose legislation that will require utility customers to subsidize the profitability of merchant  generators, such as the Millstone nuclear power plant, unless those merchant generators demonstrate the need to their customers and the state with financial reports that show their actual loss in profits?

![aarp-logo-with-ct-75x75](https://cloud.githubusercontent.com/assets/22284125/19608565/32cb04c4-97a0-11e6-980b-f83996d49077.jpg)

**Comment by doughardy-ctnj** [comment]
I am still unable to log in as a candidate on either laptop - i'm sure it's something that can be fixed.

**Comment by doughardy-ctnj** [comment]
Another question for the list:

Does Connecticut have a revenue problem or a spending problem?

**Comment by doughardy-ctnj** [comment]
Another question:

Community College students recently won a reprieve but are facing the possibility of a significant tuition hike. What are you planning to do to ensure that community college remains an affordable option for families?

**Comment by mzagaja** [comment]
Ok I rejiggered the permissions by removing and re-adding you to Toni Walker. Go to https://enigmatic-escarpment-35887.herokuapp.com/candidates/371/edit and see if it works now

**Comment by doughardy-ctnj** [comment]
still getting error message just trying to get to the link

**Comment by doughardy-ctnj** [comment]
btw, a search function would be good. most folks don't know the district number connected to anyone - even if they're not looking for their own district

**Comment by doughardy-ctnj** [comment]
just thinking out loud here - but maybe i should use a different email? 

or, should i not try to access using a private tab? I have yet to reach the candidate interface. Is it a permissions thing, security you built in?

**Comment by mzagaja** [comment]
You have to login, then after you login access that link. Often times private tabs will forget the login credentials and fail to carry them over from the session.

**Comment by doughardy-ctnj** [comment]
i open vote.ctnewsjunkie.com and login
i copy the url for the candidate login screen and paste it into address bar in same window where i just logged in
still get error message

**Comment by mzagaja** [comment]
That's the problem, you need to login on the staging website not vote.ctnewsjunkie.com: https://enigmatic-escarpment-35887.herokuapp.com/users/sign_in

**Comment by doughardy-ctnj** [comment]
it worked finally

**Comment by doughardy-ctnj** [comment]
i filled in some dummy text - answers did not populate:

https://enigmatic-escarpment-35887.herokuapp.com/districts/93

**Comment by mzagaja** [comment]
Ok that was a bug with the questions not populating. Should be fixed now, try again. Also added the AARP questions.

**Comment by doughardy-ctnj** [comment]
looks good

**Comment by mzagaja** [comment]
Awesome. I will (finally!) close this out and any updates can be new issues.

**Comment by mzagaja** [comment]
So my friends showed up early blowing my window tonight but yes an incognito window will break it since it will likely fail to retain your login session. 

-Matt

**Comment by doughardy-ctnj** [comment]
OK understood - I told AARP we'd be ready to launch no sooner than Thursday
morning, but I think we have a long way to go on solving final issues. And
they're massaging their disclaimer language as well - final language to
come today I think.

The email we send out to the campaigns should provide them with a link to
have them contact us if they're having a problem.

At some point, I should be able to set up their accounts for them and clear
problems.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=2ac66c29-0a30-47bb-ffef-6e594839b8b2>
(860) 543-9453 (mobile)
